### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by baztian** [madhead/docker-oracle-xe#1]
`docker logs` gives me

    Fri Jan  9 23:48:32 UTC 2015
    /etc/init.d/oracle-xe: line 69: /etc/init.d/functions: No such file or directory
    Starting Oracle Net Listener.
    Starting Oracle Database 11g Express Edition instance.

Oracle doesn't seem to listen on the ports I've mapped

**Comment by madhead** [comment]
@baztian can you please share the action's you've taken to start the container? Is this a full log?

**Comment by baztian** [comment]
Yes this is a full log.

    git clone https://github.com/madhead/docker-oracle-xe.git
    cd docker-oracle-xe
    mkdir rpm && cd rpm
    curl -L -O https://github.com/madhead/docker-oracle-xe/releases/download/v1.0.0/oracle-xe-11.2.0-1.0.x86_64.rpm.tar.gz
    cd -
    docker build -t "madhead/docker-oracle-xe" .
    docker run -d --name ora -p 49161:1521 -p 49162:8080 madhead/docker-oracle-xe
    docker logs ora

**Comment by madhead** [comment]
@baztian Interesting. I've got the same logs:
```
┌[madhead@madhead-mint:~]
└─$ docker logs ora
Sat Jan 10 00:08:35 GMT 2015
/etc/init.d/oracle-xe: line 69: /etc/init.d/functions: No such file or directory
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
```
But the instance is up and I can actually connect to it (I use DBeaver). Also, running `ps axu` from the host system results in this:
```
┌[madhead@madhead-mint:~]
└─$ ps axu | grep ora 
madhead  20556  0.0  0.1 218012  7912 ?        Ssl  03:08   0:00 /u01/app/oracle/product/11.2.0/xe/bin/tnslsnr LISTENER -inherit
```
Can you please check `ps`?

**Comment by baztian** [comment]
Output is

    me    28879  0.0  0.3 218012 13156 ?        Ssl  01:19   0:00 /u01/app/oracle/product/11.2.0/xe/bin/tnslsnr LISTENER -inherit
    me    28956  0.1  0.6 425916 20836 ?        Ss   01:19   0:00 oracleXE (LOCAL=NO)

I'm using Oracle SQL Developer. Apex doesn't work either.

**Comment by baztian** [comment]
I get the following error in sqldeveloper

An error was encountered performing the requested operation:

ORA-01033: ORACLE initialization or shutdown in progress
01033. 00000 -  "ORACLE initialization or shutdown in progress"
*Cause:    An attempt was made to log on while Oracle is being started up
           or shutdown.
*Action:   Wait a few minutes. Then retry the operation.
Vendor code 1033

**Comment by madhead** [comment]
@baztian sorry, cannot help you with this, cannot reproduce.

**Comment by baztian** [comment]
As a workaround I'm currently using the image arahman/docker-oracle-xe-11g. It works without problems.

**Comment by bric3** [comment]
I did see the same log errors when building the Oracle image, however I can use just fine oracle.

Also I encountered _apparmor_ troubles when playing with docker & systemd to run this image as a service. I ended up start / stopping docker manually, as I'm not proficient in apparmor config.

**Comment by anthony-o** [comment]
I've got the same problem but a bit more weird.
Actually, I try the `Dockerfile` on Ubuntu 14.04.2 (my main OS) and manage to start Oracle XE BUT, if I build the `Dockerfile` in a Ubuntu 14.04.2 inside a VirtualBox on my main OS, then here are the strange logs when executing step `RUN yum localinstall -y /tmp/oracle-xe-11.2.0-1.0.x86_64.rpm ...`:

```
sysctl: setting key "kernel.sem": Read-only file system
/var/tmp/rpm-tmp.h5t4yQ: line 257: [: 18446744073692774399: integer expression expected
/var/tmp/rpm-tmp.h5t4yQ: line 271: [: 18446744073692774399: integer expression expected
sysctl: setting key "fs.file-max": Read-only file system
```

and the strange logs when executing step `RUN /etc/init.d/oracle-xe configure...`:

```
Starting Oracle Net Listener...Done
Configuring database...grep: /u01/app/oracle/product/11.2.0/xe/config/log/*.log: No such file or directory
grep: /u01/app/oracle/product/11.2.0/xe/config/log/*.log: No such file or directory
Done
/bin/chmod: cannot access '/u01/app/oracle/oradata': No such file or directory
/bin/chmod: cannot access '/u01/app/oracle/diag': No such file or directory
Starting Oracle Database 11g Express Edition instance...Done
```

Those errors happens only in my VirtualBox Ubuntu, and not in my main Ubuntu. In the VirtualBox, after building the image, if I run the image interactivly (`sudo docker run --detach=false --rm=true --interactive=true --tty=true madhead/docker-oracle-xe /bin/bash`) and execute the `start.sh` script here is the result:

```
bash-4.2# /start.sh 
Thu May 28 17:17:45 UTC 2015
/etc/init.d/oracle-xe: line 69: /etc/init.d/functions: No such file or directory
Starting Oracle Net Listener.
Starting Oracle Database 11g Express Edition instance.
Failed to start Oracle Net Listener using /u01/app/oracle/product/11.2.0/xe/bin/tnslsnr and Oracle Express Database using /u01/app/oracle/product/11.2.0/xe/bin/sqlplus.
```

**Comment by anthony-o** [comment]
More debug information, lines 257 & 271 of the rpm script correspond to a `-lt` test on `shmax` and `shmall` variables which are obtained with:

```
shmmax=`cat /proc/sys/kernel/shmmax`
shmall=`cat /proc/sys/kernel/shmall`
```

In my VirtualBox here is the value:

```
# cat /proc/sys/kernel/shmmax
18446744073692774399
# cat /proc/sys/kernel/shmall
18446744073692774399
```

And in my main host:

```
$ cat /proc/sys/kernel/shmmax
33554432
$ cat /proc/sys/kernel/shmall 
2097152
```

**Comment by anthony-o** [comment]
The main difference between my host & virtual machine is the version of Linux:
* `3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` in my virtual machine
* `3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` in my host (I've not yet rebooted it after updates :p )

As stated [here](https://github.com/docker/docker/issues/10176#issuecomment-75071610) it seems the kernel 3.16 [changed](https://git.kernel.org/cgit/linux/kernel/git/mhocko/mm.git/commit/include/uapi/linux/shm.h?id=060028bac94bf60a65415d1d55a359c3a17d5c31) something on those values...

**Comment by anthony-o** [comment]
Finally, I upgraded docker in my virtual machine then the build passed without the "`No such file or directory`" problem and run correctly.

I used docker given by Ubuntu 14.04.2 (`version 1.0.1, build 990021a`) then did:

```bash
wget -qO- https://get.docker.io/gpg | sudo apt-key add -
sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
sudo apt-get update
sudo apt-get install lxc-docker
```

and now I'm at `version 1.6.2, build 7c8fca2`.

What's still strange is that I didn't had those problems with the same docker version (`1.0.1`) on my host with Linux `3.13`...

**Comment by saschamonteiro** [comment]
if you still have issues with setting key "kernel.**": Read-only file system, set them to the correct value on the host system, then the container doesn't have to try and set them (which it can't)

**Comment by wharsojo** [comment]
@madhead 
I create a [PR](https://github.com/madhead/docker-oracle-xe/pull/7) to fix:
- /etc/init.d/oracle-xe: line 69: /etc/init.d/functions: No such file or directory
- cannot touch '/var/lock/subsys/listener': No such file or directory
- /etc/init.d/oracle-xe: line 362: netstat: command not found

Thanks,
Widi Harsojo.
[myboot2docker](https://github.com/wharsojo/myboot2docker)
