### ISSUE TITLE
Make image available in docker hub

### ISSUE THREAD

**Issue by shartte** [madhead/docker-oracle-xe#2]
It would be nice if your image was available in the Docker hub, so it could be installed using docker pull. But for some reason I get the following error:

    FATA[0004] Tag latest not found in repository madhead/docker-oracle-xe

I was succesful in building it myself and running it however. Thanks a lot for this great image!

**Comment by madhead** [comment]
@shartte, thank you!

Unfortunately, it fails to build on Docker Hub as Oracle won't install on a systems with less then 2GB of swap. I have no ideas of how to overcome this. The only solution is to use another base image with manually created swapfile.

**Comment by wyaeld** [comment]
I don't advise trying to do that - if you redistribute the binary there you'll just end up with an angry letter from Oracle's lawyers.

**Comment by madhead** [comment]
But there are already a couple of Oracle XE images on Docker Hub...

**Comment by pazthor** [comment]
Hi, I have a same problem and finded this:
http://stackoverflow.com/questions/28952330/docker-search-finds-image-but-cant-pull

I hope they serve

**Comment by madhead** [comment]
Well, looks like it's not possible to redistribute Oracle due to some laws
