### ISSUE TITLE
Use volume for Oracle data

### ISSUE THREAD

**Issue by madhead** [madhead/docker-oracle-xe#8]
https://docs.docker.com/userguide/dockervolumes/

**Comment by madhead** [comment]
Well, Oracle scatters it's data: there is no single directory which can be `VOLUME`d easyly. So, let's not change anything.

**Comment by bayclosed** [comment]
Thank you for the repo.
I [forked it](https://github.com/bayclosed/docker-oracle-xe) and added volume support:
all the scattered data dirs and almost all log dirs are moved into /oracle volume

    ~ # ls -1 /oracle/
    admin
    diag
    etc.oracle-xe
    fast_recovery_area
    oradata
    product_11.2.0_xe_config_log
    product_11.2.0_xe_dbs
    product_11.2.0_xe_log
    product_11.2.0_xe_network_admin

symlinks at the original places to them are being [re-]created upon each container startup.

**Comment by madhead** [comment]
@bayclosed that sounds pretty cool. PR?
