### ISSUE TITLE
Need to create oracle:dba user in Dockefile

### ISSUE THREAD

**Issue by rue-stephen** [madhead/docker-oracle-xe#9]
The install failed initially with `chown: invalid user: 'oracle:dba'`.

I had to add
```
RUN groupadd dba
RUN useradd -G dba oracle
```

to the `Dockerfile`.

**Comment by madhead** [comment]
Can you please check that Oracle installation was ok when you got that error? These user / group should have been created with RPM installer automatically.

**Comment by rue-stephen** [comment]
It works now. You're right. Thanks!
